# 1. Análisis Exploratorio de Datos (EDA) Inicial

El objetivo de esta fase es entender exactamente qué contiene nuestra base de datos antes de aplicar cualquier modificación o limpieza.

Trabajaremos con el archivo dataset_bancario_empresarial.xlsx, un documento de Excel enfocado en registros transaccionales que permite rastrear el flujo de dinero, identificar qué transacciones cruzaron exitosamente con el banco y cuáles presentan anomalías.

Ruta de trabajo:

- Diagnóstico inicial: Carga del archivo, revisión de dimensiones y tipos de datos.

- Auditoría de calidad: Identificación rápida de nulos, duplicados y posibles errores de formato.

- Comportamiento base: Exploración estadística rápida de las variables clave.

In [1]:
# Importar las librerías
import pandas as pd
import numpy as np

In [1]:
# Importar las librerías
import pandas as pd
import numpy as np

In [2]:
# Cargar la base de datos
df = pd.read_excel("dataset_bancario_empresarial.xlsx")
# Mostrar la tabla
df.head()

,transaccion_id,fecha_operacion,fecha_contable,empresa_id,empresa,cuenta_bancaria,banco,tipo_movimiento,categoria,proveedor_cliente,...,pais,responsable,estado_conciliacion,fecha_vencimiento,dias_mora,nivel_riesgo,canal,observaciones,requiere_revision,motivo_revision
0,TRX-001,2026-01-07,2026-01-07,EMP-002,Logistica Prisma Ltda.,1002-553311,Banco Capital,Egreso,Nomina,Servicios Beta,...,Colombia,Carlos Pena,Conciliado,2025-12-31,0,Bajo,PSE,NaN,No,NaN
1,TRX-002,2026-01-10,2026-01-10,EMP-003,Insumos Horizonte S.A.,1003-902244,Banco Pacifico,Egreso,Impuestos,Aduanas Global,...,Colombia,Diana Torres,Conciliado,2026-01-08,0,Bajo,Transferencia,NaN,No,NaN
2,TRX-003,2026-01-13,2026-01-13,EMP-001,Nova Retail S.A.S.,1001-884422,Banco Nacional,Egreso,Servicios publicos,Energia Urbana,...,Colombia,Felipe Mora,Conciliado,2026-01-16,0,Bajo,Tarjeta,NaN,No,NaN
3,TRX-004,2026-01-16,2026-01-17,EMP-002,Logistica Prisma Ltda.,1002-553311,Banco Andino,Egreso,Arriendo,Talento Humano,...,Colombia,NaN,Pendiente,2026-01-24,159,Medio,Debito automatico,NaN,Si,Conciliacion no cerrada
4,TRX-005,2026-01-19,2026-01-19,EMP-003,Insumos Horizonte S.A.,1003-902244,Banco Capital,Ingreso,Credito bancario,Arrendadora Centro,...,Colombia,Ana Ruiz,Conciliado,2026-02-01,0,Bajo,Caja,NaN,No,NaN

In [6]:
# Tamaño de la base (filas, columnas)
df.shape

(150, 28)

In [9]:
# Nombre de las columnas
print(df.columns.tolist())

['transaccion_id', 'fecha_operacion', 'fecha_contable', 'empresa_id', 'empresa', 'cuenta_bancaria', 'banco', 'tipo_movimiento', 'categoria', 'proveedor_cliente', 'documento_ref', 'moneda', 'valor_bruto', 'impuesto_iva', 'valor_neto', 'metodo_pago', 'centro_costo', 'ciudad', 'pais', 'responsable', 'estado_conciliacion', 'fecha_vencimiento', 'dias_mora', 'nivel_riesgo', 'canal', 'observaciones', 'requiere_revision', 'motivo_revision']

In [8]:
#Tipos de datos
df.dtypes

transaccion_id                 object
fecha_operacion        datetime64[ns]
fecha_contable         datetime64[ns]
empresa_id                     object
empresa                        object
cuenta_bancaria                object
banco                          object
tipo_movimiento                object
categoria                      object
proveedor_cliente              object
documento_ref                  object
moneda                         object
valor_bruto                     int64
impuesto_iva                  float64
valor_neto                    float64
metodo_pago                    object
centro_costo                   object
ciudad                         object
pais                           object
responsable                    object
estado_conciliacion            object
fecha_vencimiento      datetime64[ns]
dias_mora                       int64
nivel_riesgo                   object
canal                          object
observaciones                  object
requiere_revision              object
motivo_revision                object
dtype: object

In [10]:
#Valores nulos
df.isnull().sum()

transaccion_id           0
fecha_operacion          0
fecha_contable           0
empresa_id               0
empresa                  0
cuenta_bancaria          0
banco                    0
tipo_movimiento          0
categoria                0
proveedor_cliente       13
documento_ref            6
moneda                   0
valor_bruto              0
impuesto_iva             0
valor_neto               0
metodo_pago              0
centro_costo            29
ciudad                   0
pais                     0
responsable             34
estado_conciliacion      0
fecha_vencimiento        0
dias_mora                0
nivel_riesgo             0
canal                    0
observaciones          136
requiere_revision        0
motivo_revision         66
dtype: int64

In [11]:
#Duplicados
df.duplicated().sum()

0

In [12]:
#Valores únicos
df.nunique()

transaccion_id         150
fecha_operacion        150
fecha_contable         105
empresa_id               3
empresa                  3
cuenta_bancaria          3
banco                    4
tipo_movimiento          2
categoria               10
proveedor_cliente       10
documento_ref          144
moneda                   2
valor_bruto            150
impuesto_iva            56
valor_neto             150
metodo_pago              5
centro_costo             5
ciudad                   5
pais                     1
responsable              4
estado_conciliacion      5
fecha_vencimiento      117
dias_mora               51
nivel_riesgo             3
canal                    6
observaciones            2
requiere_revision        2
motivo_revision         10
dtype: int64

In [13]:
#Variables numéricas
df.describe()

,fecha_operacion,fecha_contable,valor_bruto,impuesto_iva,valor_neto,fecha_vencimiento,dias_mora
count,150,150,1.500000e+02,1.500000e+02,1.500000e+02,150,150.000000
mean,2026-03-24 20:00:00,2026-03-25 12:00:00,-1.027602e+06,-7.371649e+04,-1.101318e+06,2026-04-01 17:36:00,32.033333
min,2026-01-05 00:00:00,2026-01-05 00:00:00,-9.364357e+06,-1.765561e+06,-1.105798e+07,2025-12-30 00:00:00,0.000000
25%,2026-02-11 06:00:00,2026-02-12 00:00:00,-5.156276e+06,0.000000e+00,-5.536686e+06,2026-02-19 06:00:00,0.000000
50%,2026-03-20 12:00:00,2026-03-21 00:00:00,-1.115285e+06,0.000000e+00,-1.214403e+06,2026-03-28 00:00:00,0.000000
75%,2026-05-03 12:00:00,2026-05-04 06:00:00,2.207024e+06,0.000000e+00,2.476772e+06,2026-05-11 06:00:00,65.750000
max,2026-06-28 00:00:00,2026-06-28 00:00:00,9.436290e+06,1.738226e+06,1.088678e+07,2026-07-23 00:00:00,170.000000
std,NaN,NaN,5.047315e+06,5.651469e+05,5.390905e+06,NaN,51.662874

In [14]:
#Todas las variables
df.describe(include="all")

,transaccion_id,fecha_operacion,fecha_contable,empresa_id,empresa,cuenta_bancaria,banco,tipo_movimiento,categoria,proveedor_cliente,...,pais,responsable,estado_conciliacion,fecha_vencimiento,dias_mora,nivel_riesgo,canal,observaciones,requiere_revision,motivo_revision
count,150,150,150,150,150,150,150,150,150,137,...,150,116,150,150,150.000000,150,150,14,150,84
unique,150,NaN,NaN,3,3,3,4,2,10,10,...,1,4,5,NaN,NaN,3,6,2,2,10
top,TRX-001,NaN,NaN,EMP-002,Logistica Prisma Ltda.,1002-553311,Banco Capital,Egreso,Credito bancario,Servicios Beta,...,Colombia,Carlos Pena,Conciliado,NaN,NaN,Bajo,PSE,Valor reportado por banco no coincide con ERP,Si,Conciliacion no cerrada
freq,1,NaN,NaN,50,50,50,38,93,28,14,...,150,29,95,NaN,NaN,101,25,8,84,42
mean,NaN,2026-03-24 20:00:00,2026-03-25 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2026-04-01 17:36:00,32.033333,NaN,NaN,NaN,NaN,NaN
min,NaN,2026-01-05 00:00:00,2026-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2025-12-30 00:00:00,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,2026-02-11 06:00:00,2026-02-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2026-02-19 06:00:00,0.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,2026-03-20 12:00:00,2026-03-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2026-03-28 00:00:00,0.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,2026-05-03 12:00:00,2026-05-04 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2026-05-11 06:00:00,65.750000,NaN,NaN,NaN,NaN,NaN
max,NaN,2026-06-28 00:00:00,2026-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2026-07-23 00:00:00,170.000000,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,51.662874,NaN,NaN,NaN,NaN,NaN

In [17]:
# Explorar variables

print("--- BANCOS REGISTRADOS ---")
print(df["banco"].unique())

print("\n--- CIUDADES REGISTRADAS ---")
print(df["ciudad"].unique())

print("\n--- TIPOS DE MOVIMIENTO ---")
print(df["tipo_movimiento"].value_counts())

--- BANCOS REGISTRADOS ---
['Banco Capital' 'Banco Pacifico' 'Banco Nacional' 'Banco Andino']

--- CIUDADES REGISTRADAS ---
['Medellin' 'Cali' 'Barranquilla' 'Cartagena' 'Bogota']

--- TIPOS DE MOVIMIENTO ---
tipo_movimiento
Egreso     93
Ingreso    57
Name: count, dtype: int64

In [20]:
# Explorar variables

df["ciudad"].value_counts()

ciudad
Medellin        30
Cali            30
Barranquilla    30
Cartagena       30
Bogota          30
Name: count, dtype: int64

In [21]:
# Explorar variables
df["banco"].value_counts()

banco
Banco Capital     38
Banco Pacifico    38
Banco Nacional    37
Banco Andino      37
Name: count, dtype: int64

In [22]:
# Ver cuántos pendientes, diferencias, rechazados y conciliados hay
print(df['estado_conciliacion'].value_counts())

estado_conciliacion
Conciliado    95
Pendiente     33
Diferencia    11
Rechazado      7
Duplicado      4
Name: count, dtype: int64

In [23]:
#Alertas por días de mora mayor a 30:
alertas_mora = df[df['dias_mora'] > 30]
print(f"Casos con mora crítica (>30 días): {len(alertas_mora)}")

Casos con mora crítica (>30 días): 45